#!/bin/sh -


readonly _command="${0##*/}"
readonly _version='0.1.7'

#give you some color see see
RED=$(printf '\033[31m')
GREEN=$(printf '\033[32m')
YELLOW=$(printf '\033[33m')
BLUE=$(printf '\033[34m')
BOLD=$(printf '\033[1m')
DIM=$(printf '\033[2m')
UNDER=$(printf '\033[4m')
RESET=$(printf '\033[m')


if [ ! -t 0 ]; then
	#case "$(readlink "/proc/$$/exe")" in
	#unfortunately, it can only run on linux, but i want run on ios or macos
	case "$(basename "$(echo "$(ps -p $$ -o command=)" | awk '{print $1}')")" in
		dash)
			while IFS= read -r line || [ -n "$line" ]; do
				_incoming="$_incoming$line"'\n'
			done
			_incoming="$(printf '%b\n' "${_incoming}")"
		;;
		sh)
			if readlink "$(which sh)" | grep -q 'dash$'; then
				while IFS= read -r line || [ -n "$line" ]; do
					_incoming="$_incoming$line"'\n'
				done
				_incoming="$(printf '%b\n' "${_incoming}")"
			else
				read -d $'\0' -r _incoming
			fi
		;;
		*)
			read -d $'\0' -r _incoming
		;;
	esac
fi

#I only wrote the APT method to get the version number, but I didn't use other system.
#emmmmmmmm
_get_package_version(){
	if [ "${1}" = 'sh' ]; then
		_command2="$(readlink "$(which sh)")"
		_command2="${_command2##*/}"
	else
		_command2="${1}"
	fi
	#If it is not Debian, return the unknown version directly
	if which dpkg 2>>/dev/null 1>>/dev/null; then
		if dpkg -s "${_command2}" 2>>/dev/null 1>>/dev/null; then
			echo "${_command2}/$(dpkg -s "${_command2}" | grep '^Version: ' | sed 's#Version: ##')"
		else
			_command_p="$(which "${_command2}")"
			if ! dpkg -S "${_command_p}" 2>>/dev/null 1>>/dev/null; then
				echo "${_command2}/unknown"
			else
				_command_p="$(dpkg -S "${_command_p}")"
				_command_p="${_command_p##*/}"
				echo "${_command2}/$(dpkg -s "${_command_p}" | grep '^Version: ' | sed 's#Version: ##')"
			fi
		fi
	else
		echo "${_command2}/unknown"
	fi
	unset _command2 _command_p
}

_user_agent="$(_get_package_version 'curl') $(uname -s)/$(uname -r) $(_get_package_version "$(basename "$(echo "$(ps -p $$ -o command=)" | awk '{print $1}')")") ${_command}/${_version}(shell script)"
#The default encryption in Bark App is like this, copy it first
_server='api.day.app'
_use_request='GET'
_encryption_algorithm='aes-128'
_encryption_mode='cbc'
_encryption_padding='pkcs7'


_print_help(){
	echo "Usage: ${_command} [OPTIONS...]
	-h	--help				Print this help
	-X	--request <method>		Specify request method to use
	-k	--key				Specify the device key to push to
	-1	--title				Specify the title to be push
	-2	--body				Specify the content to be push
	-l	--level				Specify the interruption level of the push
	-b	--badge				Specify the app badge (will overwrite the existing one)
	-a	--autocopy			Specify whether to enable auto-copy
	-c	--copy				Specify the content to be copied to the clipboard
	-s	--sound				Specify the custom ringtone
	-i	--icon				Specify the URL of the custom icon
	-g	--group				Specify the notification group
	-i2	--isarchive			Specify whether to save to the app
	-u	--url				Specify the URL to jump to when clicked
	-s2	--server			Specify the server used to forward messages
	-ea	--encryption-algorithm		Specify the algorithm used during encryption <AES128/AES192/AES256>
	-em	--encryption-mode		Specify the mode used during the encryption process <CBC/ECB>
	-ep	--encryption-padding		Specify the padding used during encryption process <pkcs7>
	-ek	--encryption-key		Specify the key used for encryption
	-ei	--encryption-iv			Specify the iv used for encryption
Example:
	${_command} -k key -1 test_title -2 test_body
	echo 'test_body' | ${_command} -k key -1 test_title
	${_command} -X GET -k key -1 test_title -2 test_body
	echo 'test_body' | ${_command} -X POST -k key -1 test_title"
}

_transform_url_encoded(){
	printf %s "${1}" | jq -s -R -r @uri
}

_GET(){
	if [ -n "${_title}" ]; then
		_title="$(_transform_url_encoded "${_title}")/"
	fi
	_body="$(_transform_url_encoded "${_body}")"
	echo "${2}: $(curl -s -X GET "https://${_server}/${1}/${_title}${_body}$(echo "${_parameter}" | sed 's#^&#?#')" -H "User-Agent: ${_user_agent}")"
}

_POST(){
	echo "${2}: $(curl -s -X POST "https://${_server}/${1}" -H "User-Agent: ${_user_agent}" -H 'Content-Type: application/json; charset=utf-8' -d "$(jo -n -- -s "title=${_title}" -s "body=${_body}" -s "level=${_level}" -n "badge=${_badge}" -n "autoCopy=${_autocopy}" -s "copy=${_copy}" -s "sound=${_sound}" -s "icon=${_icon}" -s "group=${_group}" -n "isArchive=${_isarchive}" -s "url=${_url}")")"
}

_encryption(){
	echo "${2}: $(curl -s --data-urlencode "ciphertext=$(echo -n "$(jo -n -- -s "title=${_title}" -s "body=${_body}" -s "level=${_level}" -n "badge=${_badge}" -n "autoCopy=${_autocopy}" -s "copy=${_copy}" -s "sound=${_sound}" -s "icon=${_icon}" -s "group=${_group}" -n "isArchive=${_isarchive}" -s "url=${_url}")" | openssl enc "-${_encryption_algorithm}-${_encryption_mode}" -K "$(printf "${_encryption_key}" | xxd -ps -c 200)" -iv "$(printf "${_encryption_iv}" | xxd -ps -c 200)" | base64)" "http://${_server}/${1}")"
}

if [ "${#}" = '0' ]; then
	_print_help
	exit 1
fi
while [ "${#}" -gt '0' ]; do
	case "${1}" in
		-h)
			_print_help
			exit 0
		;;
		-k|--key)
			if [ -z "${_keys}" ]; then
				_keys="${2}"
			else
				_keys="${_keys} ${2}"
			fi
		;;
		-1|--title)
			_title="${2}"
		;;
		-2|--body)
			_body="${2}"
		;;
		-l|--level)
			_level="${2}"
			_parameter="${_parameter}&level=${2}"
		;;
		-b|--badge)
			_badge="${2}"
			_parameter="${_parameter}&badge=${2}"
		;;
		-a|--autocopy)
			_autocopy="${2}"
			_parameter="${_parameter}&autoCopy=${2}"
		;;
		-c|--copy)
			_copy="${2}"
			_parameter="${_parameter}&copy=${2}"
		;;
		-s|--sound)
			_sound="${2}"
			_parameter="${_parameter}&sound=${2}"
		;;
		-i|--icon)
			_icon="${2}"
			_parameter="${_parameter}&icon=$(_transform_url_encoded "${2}")"
		;;
		-g|--group)
			_group="${2}"
			_parameter="${_parameter}&group=${2}"
		;;
		-i2|--isarchive)
			_isarchive="${2}"
			_parameter="${_parameter}&isArchive=${2}"
		;;
		-u|--url)
			_url="${2}"
			_parameter="${_parameter}&url=${2}"
		;;
		-s2|--server)
			_server="${2}"
		;;
		-ea|--encryption-algorithm)
			case "${2}" in
				AES128|aes128|128)
					_encryption_algorithm='aes-128'
					;;
				AES192|aes192|192)
					_encryption_algorithm='aes-192'
					;;
				AES256|aes256|256)
					_encryption_algorithm='aes-256'
					;;
				*)
					echo "${RED}Error: invalid encryption algorithm${RESET}" 1>&2
					exit 1
					;;
			esac
		;;
		-em|--encryption-mode)
			case "${2}" in
				CBC|cbc)
					_encryption_mode='cbc'
					;;
				ECB|ecb)
					_encryption_mode='ecb'
					;;
				*)
					echo "${RED}Error: invalid encryption mode${RESET}" 1>&2
					exit 1
					;;
			esac
		;;
		-ep|--encryption-padding)
			#But it seems only pkcs7? Generally, this variable can be skipped directly or not, it should be okay
			case "${2}" in
				pkcs7)
					_encryption_padding='pkcs7'
					;;
				*)
					echo "${RED}Error: invalid encryption padding${RESET}" 1>&2
					exit 1
					;;
			esac
		;;
		-ek|--encryption-key)
			_encryption_key="${2}"
		;;
		-ei|--encryption-iv)
			_encryption_iv="${2}"
		;;
		-X)
			case "${2}" in
				GET)
					_use_request='GET'
					;;
				POST)
					_use_request='POST'
					;;
				encryption)
					_use_request='POST_encryption'
					;;
				*)
					echo "${RED}Error: invalid request method${RESET}" 1>&2
					echo 'Please use "GET", "POST" or "encryption"'
					exit 1
					;;
			esac
		;;
		*)
			_skip='1'
			shift 1
		;;
	esac
	if [ "${_skip}" = '1' ]; then
		unset _skip
	else
		shift 2
	fi
done
if [ -n "${_incoming}" ]; then
	_body="${_incoming}"
	unset _incoming
fi
if [ -n "${ZSH_VERSION:-}" ]; then
	setopt shwordsplit
fi
for _key in ${_keys}; do
	_key_first="$(expr substr "${_key}" 1 4)"
	_key_last="$(echo "${_key}" | tail -c 5)"
	_key2="${_key_first}xxxx${_key_last}"
	case "${_use_request}" in
		GET)
			_GET "${_key}" "${_key2}" &
			;;
		POST)
			_POST "${_key}" "${_key2}" &
			;;
		POST_encryption)
			_encryption "${_key}" "${_key2}" &
			;;
	esac
	unset _key_first _key_last _key_middle _key _key2
done
wait
